FROM node:16.13.1-alpine3.14 AS build-env
ARG VITE_CLIENT_SIDE_API_URL
ARG VITE_SERVER_SIDE_API_URL
WORKDIR /app
COPY . .
RUN npm ci && npm run build

FROM gcr.io/distroless/nodejs:16
WORKDIR /app
COPY --from=build-env /app/build .
COPY --from=build-env /app/package.json .
CMD [ "index.js" ]
