version: "3.9"

services:
  api:
    build: ./api
    container_name: api-prod
    environment:
      - CLIENT_CORS_DOMAIN=http://localhost
      - PORT=8000
      - RELOAD=False
    expose:
      - 8000
    image: aasm-website-api
    networks:
      - proxynet-prod
    restart: always

  client:
    build:
      args:
        - VITE_CLIENT_SIDE_API_URL=http://localhost/api
        - VITE_SERVER_SIDE_API_URL=http://proxy/api
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client-prod
    expose:
      - 3000
    image: aasm-website-client
    networks:
      - proxynet-prod
    restart: always

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    container_name: proxy-prod
    depends_on:
      - api
      - client
    expose:
      - 80
    image: aasm-website-proxy
    networks:
      - proxynet-prod
    ports:
      - "80:80"
    restart: always

networks:
  proxy-net-prod:
