version: "3.9"

services:
  api:
    build: ./api
    container_name: api
    environment:
      - CLIENT_CORS_DOMAIN=https://agents-assembly.com
      - PORT=8000
      - RELOAD=False
    expose:
      - 8000
    image: aasm/aasm-website-api
    networks:
      - proxynet
    restart: always

  client:
    build:
      args:
        - VITE_CLIENT_SIDE_API_URL=https://agents-assembly.com/api
        - VITE_SERVER_SIDE_API_URL=http://proxy/api
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client
    expose:
      - 3000
    image: aasm/aasm-website-client
    networks:
      - proxynet
    restart: always

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.prod
    container_name: proxy
    depends_on:
      - api
      - client
    expose:
      - 80
    image: aasm/aasm-website-proxy
    networks:
      - proxynet
    ports:
      - "80:80"
    restart: always

networks:
  proxynet:
