version: "3.9"

services:
  api:
    container_name: api
    environment:
      - CLIENT_CORS_DOMAIN=https://agents-assembly.com
      - PORT=8000
      - RELOAD=False
    expose:
      - 8000
    image: aasm/aasm-website-api
    networks:
      - proxynet
    restart: always

  client:
    container_name: client
    expose:
      - 3000
    image: aasm/aasm-website-client
    networks:
      - proxynet
    restart: always

  proxy:
    container_name: proxy
    depends_on:
      - api
      - client
    expose:
      - 80
    image: aasm/aasm-website-proxy
    networks:
      - proxynet
    ports:
      - "80:80"
    restart: always

networks:
  proxynet:
